[package]
name = "tesser-backtest-wasm"
edition.workspace = true
version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
description = "WebAssembly wrapper for tesser-backtest-core (browser playground)"
readme = "README.md"

[lib]
crate-type = ["cdylib"]

[dependencies]
serde.workspace = true
serde_json.workspace = true
tesser-backtest-core = { version = "0.9.3", path = "../tesser-backtest-core" }

